//
//  AuthSplashViewController.swift
//  pm-ios
//
//  Created by Synbrix Software on 1/17/20.
//  Copyright (c) 2020 Synbrix Software. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Cartography

final class AuthSplashViewController: BaseViewController {

    // MARK: - Properties -
    var viewModel: AuthSplashViewModelType? {
        didSet {
            viewModel?.viewDelegate = self
        }
    }

    // MARK: - UI Elements -
    private let logo: UIImageView = {
        let imageView: UIImageView = UIImageView()
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.backgroundColor = .clear
        imageView.image = UIImage(named: "PanicMechanicLogo")
        imageView.contentMode = .scaleAspectFit
        return imageView
    }()
    
    private let loadingIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView(style: UIActivityIndicatorView.Style.medium)
        indicator.translatesAutoresizingMaskIntoConstraints = false
        return indicator
    }()

    // MARK: - Lifecycle -
    override func loadView() {
        super.loadView()
        view.addSubview(logo)
        view.addSubview(loadingIndicator)
        layoutSubviews()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        viewModel?.start()
        setup()
    }
    
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        layoutSubviews()
    }
	
}

// MARK: - Private Helper -
extension AuthSplashViewController {

    private func layoutSubviews() {
        constrain(logo) { view in
            view.center == view.superview!.center
            view.width == view.height * 0.33
            view.leading == view.superview!.leading + 64.0
            view.trailing == view.superview!.trailing - 64.0
        }
        constrain(loadingIndicator) { view in
            view.centerX == view.superview!.centerX
            view.bottom == view.superview!.safeAreaLayoutGuide.bottom - 96.0
        }
    }
    
    private func setup() {
        view.backgroundColor = Colors.bgColor
    }
    
}

// MARK: - View Delegate -
extension AuthSplashViewController: AuthSplashViewModelViewDelegate {
    
    func startAnimating() {
        DispatchQueue.main.async {
            self.loadingIndicator.startAnimating()
        }
    }
    
}
