//
//  AuthSplashInterfaces.swift
//  pm-ios
//
//  Created by Synbrix Software on 1/17/20.
//  Copyright (c) 2020 Synbrix Software. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AuthSplashViewModelType {
    
    var viewDelegate: AuthSplashViewModelViewDelegate? { get set }
    var coordinatorDelegate: AuthSplashViewModelCoordinatorDelegate? { get set }

    func start()
    
}

protocol AuthSplashViewModelCoordinatorDelegate: class {
        
    func proceedToMain(user: AuthenticatedUser)
    func proceedToAuth()
    func proceedToTutorial(user: AuthenticatedUser)
    func proceedToPurchase()

}

protocol AuthSplashViewModelViewDelegate: class {
    func startAnimating()
}

