//
//  Colors.swift
//  pm-ios
//
//  Created by Synbrix Software on 1/20/20.
//  Copyright © 2020 Synbrix Software. All rights reserved.
//

import UIKit

/**

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=5560u0kq0icgdrQlqmxv0d8Gb84


*** Primary color:

   shade 0 = #701550 = rgb(112, 21, 80) = rgba(112, 21, 80,1) = rgb0(0.439,0.082,0.314)
   shade 1 = #AB558D = rgb(171, 85,141) = rgba(171, 85,141,1) = rgb0(0.671,0.333,0.553)
   shade 2 = #8B2E6A = rgb(139, 46,106) = rgba(139, 46,106,1) = rgb0(0.545,0.18,0.416)
   shade 3 = #510335 = rgb( 81,  3, 53) = rgba( 81,  3, 53,1) = rgb0(0.318,0.012,0.208)
   shade 4 = #320020 = rgb( 50,  0, 32) = rgba( 50,  0, 32,1) = rgb0(0.196,0,0.125)

*** Secondary color (1):

   shade 0 = #8C1A25 = rgb(140, 26, 37) = rgba(140, 26, 37,1) = rgb0(0.549,0.102,0.145)
   shade 1 = #D66A74 = rgb(214,106,116) = rgba(214,106,116,1) = rgb0(0.839,0.416,0.455)
   shade 2 = #AD3944 = rgb(173, 57, 68) = rgba(173, 57, 68,1) = rgb0(0.678,0.224,0.267)
   shade 3 = #65030C = rgb(101,  3, 12) = rgba(101,  3, 12,1) = rgb0(0.396,0.012,0.047)
   shade 4 = #3E0006 = rgb( 62,  0,  6) = rgba( 62,  0,  6,1) = rgb0(0.243,0,0.024)

*** Secondary color (2):

   shade 0 = #421761 = rgb( 66, 23, 97) = rgba( 66, 23, 97,1) = rgb0(0.259,0.09,0.38)
   shade 1 = #774E95 = rgb(119, 78,149) = rgba(119, 78,149,1) = rgb0(0.467,0.306,0.584)
   shade 2 = #592D78 = rgb( 89, 45,120) = rgba( 89, 45,120,1) = rgb0(0.349,0.176,0.471)
   shade 3 = #2B0646 = rgb( 43,  6, 70) = rgba( 43,  6, 70,1) = rgb0(0.169,0.024,0.275)
   shade 4 = #1A022B = rgb( 26,  2, 43) = rgba( 26,  2, 43,1) = rgb0(0.102,0.008,0.169)


#####  Generated by Paletton.com (c) 2002-2014

*/

struct Colors {
//    static let bgColor = UIColor(red:1.00, green:0.95, blue:0.98, alpha:1.0)
//    static let bgColor = UIColor(red:1.00, green:0.97, blue:0.99, alpha:1.0) // FFF1FA
    
    static let bgColor = UIColor(red:1.00, green:0.95, blue:0.98, alpha:1.0)
//    static let bgColor = UIColor(red:0.86, green:0.77, blue:0.83, alpha:1.0) // DBC4D3
    static let lightPanicRed = UIColor(red:0.67, green:0.33, blue:0.55, alpha:1.0)
//    static let bgColor2 = UIColor(red:0.67, green:0.33, blue:0.55, alpha:1.0) //

//    static let bgColor = UIColor(red:0.44, green:0.08, blue:0.31, alpha:0.25)
    static let opaquePink = UIColor(red:0.44, green:0.08, blue:0.31, alpha:0.5)
    static let panicRed = UIColor(red:0.44, green:0.08, blue:0.31, alpha:1.0) // 701550
//    static let actionColor = UIColor(red:0.26, green:0.12, blue:0.94, alpha:0.75)
//    static let actionColor = UIColor(red:0.26, green:0.09, blue:0.38, alpha:1.0) //421761
    static let actionColor = UIColor(red:0.44, green:0.08, blue:0.31, alpha:1.0)
}
